[package]
name = "file_encryptor"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A simple file encryption program with Caesar Cipher and XOR encryption"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
